[[mgr.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "plugin vcs-files"
desc = "Show Git file changes"

[[mgr.prepend_keymap]]
on = "<S-d>"
run = "plugin diff"
desc = "Diff the selected with the hovered file"
